<?php /* This is a PHP data file */ if (!@$LOADSTRUCT) { die("This is not a program file."); }
return array (
  '_detailPage' => '',
  '_disableAdd' => '0',
  '_disableErase' => '0',
  '_disableModify' => '0',
  '_disablePreview' => '0',
  '_disableView' => '1',
  '_filenameFields' => 'num',
  '_hideRecordsFromDisabledAccounts' => '0',
  '_indent' => '0',
  '_listPage' => '',
  '_maxRecords' => '',
  '_maxRecordsPerUser' => '',
  '_previewPage' => '',
  '_requiredPlugins' => '',
  '_tableName' => '_permalinks',
  'listPageFields' => 'permalink, tableName, recordNum, updatedDate, customSourceUrl, old',
  'listPageOrder' => 'customSourceUrl DESC, permalink',
  'listPageSearchFields' => '_all_',
  'menuHidden' => '1',
  'menuName' => 'Permalinks',
  'menuOrder' => 1361218288,
  'menuType' => 'multi',
  'num' => array(
    'order' => '1',
    'type' => 'none',
    'label' => 'Record Number',
    'isSystemField' => '1',
  ),
  'updatedDate' => array(
    'order' => '2',
    'label' => 'Updated Date',
    'type' => 'none',
  ),
  'permalink' => array(
    'order' => '3',
    'label' => 'Permalink',
    'type' => 'textfield',
    'defaultValue' => '',
    'fieldPrefix' => '',
    'description' => '',
    'fieldWidth' => '',
    'isPasswordField' => '0',
    'isRequired' => '1',
    'isUnique' => '1',
    'minLength' => '',
    'maxLength' => '',
    'charsetRule' => '',
    'charset' => '',
  ),
  'customSourceUrl' => array(
    'order' => '4',
    'label' => 'Custom Source Url',
    'type' => 'textfield',
    'defaultValue' => '',
    'fieldPrefix' => '',
    'description' => 'eg: /contact/contact.php',
    'fieldWidth' => '',
    'isPasswordField' => '0',
    'isRequired' => '0',
    'isUnique' => '0',
    'minLength' => '',
    'maxLength' => '',
    'charsetRule' => '',
    'charset' => '',
  ),
  '__separator002__' => array(
    'order' => '5',
    'label' => '',
    'type' => 'separator',
    'separatorType' => 'html',
    'separatorHeader' => '',
    'separatorHTML' => '<tr>
 <td></td>
 <td>Enter a site root-relative path to a PHP file above to manually setup a custom permalink</td>
</tr>',
  ),
  '__separator001__' => array(
    'order' => '6',
    'label' => '',
    'type' => 'separator',
    'separatorType' => 'header bar',
    'separatorHeader' => 'Internal Fields (do not modify)',
    'separatorHTML' => '<tr>
 <td colspan=\'2\'>
 </td>
</tr>',
  ),
  'tableName' => array(
    'order' => '7',
    'label' => 'Tablename',
    'type' => 'textfield',
    'defaultValue' => '',
    'fieldPrefix' => '',
    'description' => '',
    'fieldWidth' => '',
    'isPasswordField' => '0',
    'isRequired' => '0',
    'isUnique' => '0',
    'minLength' => '',
    'maxLength' => '',
    'charsetRule' => '',
    'charset' => '',
  ),
  'recordNum' => array(
    'customColumnType' => 'INT UNSIGNED NOT NULL',
    'order' => '8',
    'label' => 'Record Num',
    'type' => 'textfield',
    'defaultValue' => '0',
    'fieldPrefix' => '',
    'description' => '',
    'fieldWidth' => '',
    'isPasswordField' => '0',
    'isRequired' => '0',
    'isUnique' => '0',
    'minLength' => '',
    'maxLength' => '',
    'charsetRule' => '',
    'charset' => '',
  ),
  'old' => array(
    'order' => '1363051435',
    'label' => 'Old',
    'type' => 'checkbox',
    'fieldPrefix' => '',
    'checkedByDefault' => '0',
    'description' => 'Redirects to <a href="?menu=_permalinks&tableName_match=<?php echo urlencode(@$RECORD[\'tableName\']); ?>&recordNum_match=<?php echo urlencode(@$RECORD[\'recordNum\']); ?>&_ignoreSavedSearch=1">most recent permalink</a>',
    'checkedValue' => 'Old',
    'uncheckedValue' => '-',
  ),
);
?>